### ISSUE TITLE
Heroku Review

### ISSUE THREAD

**Issue by PLUCS2** [elonrov/Large#9]
- [x] Make sure that you can click between modals after errors
- [x] Errors on posting a story 
- [x] Should navigate to story show page on publishing 
- [x] Make sure that a story can be published 
- [x] Stories are not loading
- [x] Make sure to take out all debuggers in production code

**Comment by elonrov** [comment]
All of those are done-- remaining bug is PATCH requests are returning 404s because the story.id is undefined
